### ISSUE TITLE
converting error while training

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#102]
Hi, im trying to train my own dataset, and i recived the following msg:

loading annotations into memory...
Done (t=0.22s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 213, in train
    for datum in data_loader:
  File "/home/student/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/student/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/student/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/student/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/student/sd/yolact/data/coco.py", line 88, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/home/student/sd/yolact/data/coco.py", line 160, in pull_item
    {'num_crowds': 0, 'labels': np.array([0])})
  File "/home/student/sd/yolact/utils/augmentations.py", line 661, in __call__
    return self.augment(img, masks, boxes, labels)
  File "/home/student/sd/yolact/utils/augmentations.py", line 54, in __call__
    img, masks, boxes, labels = t(img, masks, boxes, labels)
  File "/home/student/sd/yolact/utils/augmentations.py", line 179, in __call__
    boxes[:, [0, 2]] *= (width  / img_w)
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

when i look into in i saw that boxes is Int. so it can't be casting to float.
i change it manualy but then another error appear...
what i did wrong?
thanks!

**Comment by dbolya** [comment]
That's weird. Maybe you have a really old version of numpy or something? What version do you have? Mine's 1.16.2.

**Comment by sdimantsd** [comment]
>>> import numpy
>>> numpy.version.version
'1.16.4'

**Comment by dbolya** [comment]
Hmm okay what about your python version? It's weird because I haven't seen anyone else have this issue even though it should be pretty common.

**Comment by sdimantsd** [comment]
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux

**Comment by sdimantsd** [comment]
maybe it's somthin with me json?

**Comment by dbolya** [comment]
Python version is fine. And I thought it might be an issue with the json but then I looked and all my boxes are ints in the json as well. I'll take another look to see if there are any other instances of floats in there.

**Comment by dbolya** [comment]
Only float in there is `"area"`. Are your area values floats?

**Comment by sdimantsd** [comment]
OK, @dbolya 
Thay whas my mistake. in my JSON file, the "annotations" array was empty....

Thanks you very much :-)
