### ISSUE TITLE
CUDA out of memory when trainning on TITAN Xp GPU

### ISSUE THREAD

**Issue by Summer234** [dbolya/yolact#107]
tks for your work and your helping!

now i have a question when train on coco 2017:
GPU :  TITAN Xp
CUDA: cuda9.2
Torch:1.0.1

the command was used :   python train.py --config=yolact_base_config --batch_size=1
but the follow error was occured:
loading annotations into memory...
Done (t=18.16s)
creating index...
index created!
loading annotations into memory...
Done (t=1.48s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 251, in train
    out = net(images)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\parallel\data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\zhy\yolact-master\yolact.py", line 530, in forward
    outs = self.backbone(x)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\zhy\yolact-master\backbone.py", line 122, in forward
    x = layer(x)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\zhy\yolact-master\backbone.py", line 27, in forward
    out = self.conv1(x)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 2.05 GiB (GPU 0; 12.00 GiB total capacity; 254.11 MiB already allocated; 9.35 GiB free; 782.50 KiB cached)

the other parameters were default. i dont know why this occured when training?    it worked well on test2017 while testing, and can get 33fps using yolact_darknet53_54_800000.pth

**Comment by dbolya** [comment]
That's very weird. A Titan Xp should have more than enough vram to run the base config, especially with a batch size of 1.

In fact, in your error Pytorch said it tried to allocate 2.05 GiB with 9.35 GiB free. That looks like to me like you had something else running on that GPU taking the rest of the memory up. Make sure you have nothing else running on the GPU during training.

**Comment by Summer234** [comment]
i tried again！training has the same memory problem。 while test is work well。
  nvidia-smi  detected that the GPU Volatile have 57% used when “python eval.py --trained_model=weights/forward/yolact_base_54_800000.pth --benchmark”   ，but 9% used while “python train.py --config=yolact_base_config” and the error “CUDA out of memory ” occoried at the same time， i dont know why。
is there anywhere have something special setting i havnot down？

**Comment by dbolya** [comment]
Huh that's really weird. You should definitely be able to train with the default settings on a Titan Xp, so maybe something's not configured properly with your environment? Maybe try installing pytorch with CUDA 10 instead of 9.2? Or maybe somethings clogging up the GPUm so if you haven't restarted your server in a while, that might be a good option.

**Comment by Summer234** [comment]
i troed torch1.1.0 instead of 1.0.1， and cuda 10 is used 。 then  it training well

**Comment by Summer234** [comment]
i troed torch1.1.0 instead of 1.0.1， and cuda 10 is used 。 then  it training well

**Comment by Zhang-O** [comment]
Warning: Augmentation output an example with no ground truth. Resampling...
[  2]    2420 || B: 1.841 | C: 1.949 | M: 3.569 | S: 0.477 | T: 7.836 || ETA: 31 days, 18:18:29 || timer: 0.320
[  2]    2430 || B: 1.793 | C: 1.894 | M: 3.595 | S: 0.483 | T: 7.765 || ETA: 31 days, 16:33:04 || timer: 0.315
[  2]    2440 || B: 1.820 | C: 1.912 | M: 3.620 | S: 0.483 | T: 7.835 || ETA: 31 days, 19:18:32 || timer: 1.626
[  2]    2450 || B: 1.781 | C: 1.885 | M: 3.607 | S: 0.494 | T: 7.768 || ETA: 31 days, 18:13:23 || timer: 3.919

Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 369, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 490, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/data/zhangyl/yolact-master/eval.py", line 955, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/data/zhangyl/yolact-master/eval.py", line 403, in prep_metrics
    classes, scores, boxes, masks = postprocess(dets, w, h, crop_masks=args.crop, score_threshold=args.score_threshold)
  File "/data/zhangyl/yolact-master/layers/output_utils.py", line 91, in postprocess
    masks = F.interpolate(masks.unsqueeze(0), (h, w), mode=interpolation_mode, align_corners=False).squeeze(0)
  File "/home/ubuntu/anaconda3/envs/zyl/lib/python3.6/site-packages/torch/nn/functional.py", line 2503, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 4.84 GiB (GPU 0; 7.77 GiB total capacity; 695.44 MiB already allocated; 1.49 GiB free; 4.84 GiB cached)


this is the last part info of my log; I use a 2080 and batchsize=4, torch=1.2.0, cuda=10. Is this normal or some problem with my config?

**Comment by dbolya** [comment]
@Zhang-O That just means you ran out of GPU memory. Are your original images really big? It looks like this happened when the model is interpolating from its small (550x550 images) back to the original image resolution.

It could be worth resizing your images (and labels) before training so this step doesn't take as much memory.

**Comment by Zhang-O** [comment]
I reduce the num of val dataset. And all become fine. Thank you a lot!
