### ISSUE TITLE
While loading resume weight in another environment getting issue

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [dbolya/yolact#163]
python3.7 train.py --config=yolact_base_config --resume=weights/yolact_base_761_111207_interrupt.pth --batch_size=1

/home/administrator/.local/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/administrator/Sheet_detection/yoloact_new/yolact/utils/cython_nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/administrator/.pyxbld/temp.linux-x86_64-3.7/pyrex/utils/cython_nms.c:598:
/usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Resuming training, loading weights/yolact_base_761_111207_interrupt.pth...
Begin training!

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 257, in train
    losses = criterion(out, wrapper, wrapper.make_mask())
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/Sheet_detection/yoloact_new/yolact/layers/modules/multibox_loss.py", line 128, in forward
    loc_t, conf_t, idx_t, idx, loc_data[idx])
  File "/home/administrator/Sheet_detection/yoloact_new/yolact/layers/box_utils.py", line 134, in match
    decoded_priors = decode(loc_data, priors, cfg.use_yolo_regressors) if cfg.use_prediction_matching else point_form(priors)
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed

@dbolya  Thanks

**Comment by NarasimmanSaravana1994** [comment]
@dbolya  I upgrade the torch, Now it is working for me.. Now my issue was solved.

pip install -upgrade torchvision==0.4.0

Thanks
