### ISSUE TITLE
I have a issue running with webcam

### ISSUE THREAD

**Issue by onoderay** [dbolya/yolact#217]
```
$ python eval.py --trained_model=weights/yolact_darknet53_54_800000.pth --score_threshold=0.15 --top_k=15 --video_multiframe=4 --video=0
Config not specified. Parsed yolact_darknet53_config from the file name.

Loading model... Done.
VIDEOIO ERROR: V4L2: property frame_count is not supported
Initializing model... Done.

Press Escape to close.
Processing FPS: 11.63 | Video Playback FPS: 0.00 | Frames in Buffer: 4    : cannot connect to X server 
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```
Do you have any suggestion to resolve this problem?

**Comment by dbolya** [comment]
Do you have a display attached? Or did you want to save the webcam footage to a file?

You may have a version of opencv that's compiled without the ability to use a display.

**Comment by Arunavameister** [comment]
Try uninstalling opencv first and then downloading the version with prebuilt OpenCV packages for Python
pip install opencv-contrib-python

**Comment by elhmadany** [comment]
I have another issue when I want use webcam. and my code is run only CPU, when I run this line the output is:

!python ./yolact/eval.py --trained_model=./yolact_base_54_800000.pth --score_threshold=0.15 --top_k=9 --video_multiframe=4 --video=0:video.mp4 --config=yolact_base_config --cuda=False

Loading model... Done.
Traceback (most recent call last):
  File "./yolact/eval.py", line 1044, in <module>
    evaluate(net, dataset)
  File "./yolact/eval.py", line 826, in evaluate
    savevideo(net, inp, out)
  File "./yolact/eval.py", line 778, in savevideo
    progress_bar = ProgressBar(30, num_frames)
  File "C:\Users\Mohammed\Desktop\Yolact_CPU\yolact\utils\functions.py", line 60, in __init__
    self._update_str()
  File "C:\Users\Mohammed\Desktop\Yolact_CPU\yolact\utils\functions.py", line 76, in _update_str
    num_bars = int(self.length * (self.cur_val / self.max_val))
ZeroDivisionError: division by zero


any suggestions!

**Comment by elhmadany** [comment]
!python ./yolact/eval.py --trained_model=./yolact_base_54_800000.pth --score_threshold=0.15 --top_k=9 --video_multiframe=4 --video=0 --config=yolact_base_config --cuda=False



Loading model... Done.
Initializing model... Done.


Processing FPS: 35.06 | Video Playback FPS: 0.00 | Frames in Buffer: 0    
Processing FPS: 31.05 | Video Playback FPS: 0.00 | Frames in Buffer: 0    
Traceback (most recent call last):
  File "./yolact/eval.py", line 1044, in <module>
    evaluate(net, dataset)
  File "./yolact/eval.py", line 828, in evaluate
    evalvideo(net, args.video)
  File "./yolact/eval.py", line 750, in evalvideo
    active_frames += [{'value': extract_frame(frame['value'], i), 'idx': 0} for i in range(1, args.video_multiframe)]
  File "./yolact/eval.py", line 750, in <listcomp>
    active_frames += [{'value': extract_frame(frame['value'], i), 'idx': 0} for i in range(1, args.video_multiframe)]
  File "./yolact/eval.py", line 709, in <lambda>
    extract_frame = lambda x, i: (x[0][i] if x[1][i] is None else x[0][i].to(x[1][i]['box'].device), [x[1][i]])
KeyError: 'box'
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-sxpsnzt6\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback



any suggestion to such problem?
