### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'augment_random_flip'

### ISSUE THREAD

**Issue by niliuxi** [dbolya/yolact#224]
How can I solve this problem when I am training?

Multiple GPUs detected! Turning off JIT.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
Traceback (most recent call last):
  File "/home/uroot/nlx_yolact/train.py", line 501, in <module>
    train()
  File "/home/uroot/nlx_yolact/train.py", line 175, in train
    transform=SSDAugmentation(MEANS))
  File "/home/uroot/nlx_yolact/utils/augmentations.py", line 668, in __init__
    enable_if(cfg.augment_random_flip, RandomFlip()),
AttributeError: 'Config' object has no attribute 'augment_random_flip'

**Comment by dbolya** [comment]
You have an outdated version of the config file. Download the config file fresh from the current master and copy your custom configs over.
