### ISSUE TITLE
storage has wrong size

### ISSUE THREAD

**Issue by cendelian** [dbolya/yolact#235]
Hi dbolya

I am sorry to bother you again.
I buy a new computer which have RTX2080ti
So i run the project in new computer

when i run the command:
`python train.py --config=yolact_resnet50_config --resume=weights/yolact_resnet50
_54_800000.pth --start_iter=0`

but there is a error:

**loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
Resuming training, loading weights/yolact_resnet50_54_800000.pth...
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    train()
  File "train.py", line 204, in train
    yolact_net.load_weights(args.resume)
  File "/home/cendelian/Study_CV/自动驾驶综合感知/yolact-master/yolact.py", line 515, in load_weights
    state_dict = torch.load(path)
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
_RuntimeError: storage has wrong size: expected 342948543801467925 got_ 1**

It's strange, could you help me?

**Comment by dbolya** [comment]
Looks like your weights file is corrupt. I suggest redownloading it or downloading it from the mirror.

**Comment by cendelian** [comment]
> Looks like your weights file is corrupt. I suggest redownloading it or downloading it from the mirror.

thanks
i have solved this issue

thanks`
