### ISSUE TITLE
[multibox_loss.py:656] RuntimeError because `maskiou_t_list=[]` when `use_maskiou=True`

### ISSUE THREAD

**Issue by lioneldaniel** [dbolya/yolact#259]
Hi, when training YOLACT++ on my custom dataset, I obtain the following error:

```bash
prompt$ CUDA_VISIBLE_DEVICES=0 python train.py --config=mydataset_config --batch_size=5
[...]
Initializing weights...
Begin training!

[  0]       0 || B: 7.946 | C: 21.177 | M: 9.427 | S: 3.278 | I: 0.283 | T: 42.111 || ETA: 46 days, 14:25:46 || timer: 3.146
[  0]      10 || B: 6.020 | C: 10.463 | M: 7.469 | S: 2.288 | I: 0.193 | T: 26.433 || ETA: 17 days, 2:38:58 || timer: 0.961
[layers/modules/multibox_loss.py:656] WARNING: maskiou_t_list=[]
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 305, in train
    losses = net(datum)
  File "yolact_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
[...]
  File "layers/modules/multibox_loss.py", line 159, in forward
    ret = self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, score_data, inst_data, labels)
  File "layers/modules/multibox_loss.py", line 659, in lincomb_mask_loss
    maskiou_t = torch.cat(maskiou_t_list)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]
```
No error happens when `use_maskiou=False`.
My custom dataset has few tiny objects, as tiny as 1 pixel in width or height, and 4 pixels in area.

**Comment by MuMuJun97** [comment]
@lioneldaniel  @dbolya  Have you find a way to solve the problem?
```python
    # Fast Mask Re-scoring Network
    # Inspried by Mask Scoring R-CNN (https://arxiv.org/abs/1903.00241)
    # Do not crop out the mask with bbox but slide a convnet on the image-size mask,
    # then use global pooling to get the final mask score
    'use_maskiou': False,
```

**Comment by dbolya** [comment]
Ah, the problem might be caused by `discard_mask_area` in the config since the default for YOLACT++ discards masks with less than 25 pixels in area. Try setting it to -1 and see if that helps (though training might be a little unstable).

**Comment by MuMuJun97** [comment]
@lioneldaniel @dbolya  Have you find a way to solve the problem?

The config.py : 
```python
    # Fast Mask Re-scoring Network
    # Inspried by Mask Scoring R-CNN (https://arxiv.org/abs/1903.00241)
    # Do not crop out the mask with bbox but slide a convnet on the image-size mask,
    # then use global pooling to get the final mask score
    'use_maskiou': False,
```

Error: 
```python
Traceback (most recent call last):
  File "/home/zhaomumu/论文/3D-Object-Tracking/yolact/train.py", line 541, in <module>
    train()
  File "/home/zhaomumu/论文/3D-Object-Tracking/yolact/train.py", line 344, in train
    losses = net(datum)
  File "/home/zhaomumu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaomumu/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhaomumu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaomumu/论文/3D-Object-Tracking/yolact/train.py", line 183, in forward
    losses = self.criterion(self.net, preds, targets, masks, num_crowds)
  File "/home/zhaomumu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaomumu/论文/3D-Object-Tracking/yolact/layers/modules/multibox_loss.py", line 159, in forward
    ret = self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, score_data, inst_data, labels)
  File "/home/zhaomumu/论文/3D-Object-Tracking/yolact/layers/modules/multibox_loss.py", line 656, in lincomb_mask_loss
    maskiou_t = torch.cat(maskiou_t_list)
RuntimeError: expected a non-empty list of Tensors
```

I also obtained the error when resume training `yolact_plus_base_config` with a specific weight file `yolact_plus_resnet50_54_800000.pth`

**Comment by lioneldaniel** [comment]
@MuMuJun97 : no problem with `'use_maskiou': False` during several epochs, and no problem when resuming the training.
@dbolya : no problem with `discard_mask_area=2` and `'use_maskiou': True` during several epochs, thank you!

**Comment by dzyjjpy** [comment]
@MuMuJun97 Have you solve the issue? **RuntimeError: expected a non-empty list of Tensors**

I met the same mistake as above:
Traceback (most recent call last):
  File "/home/jiapy/workspace/yolact/train.py", line 506, in <module>
    train()
  File "/home/jiapy/workspace/yolact/train.py", line 309, in train
    losses = net(datum)
  File "/home/jiapy/virtualEnv/py3.6torch1.0.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiapy/virtualEnv/py3.6torch1.0.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 139, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/jiapy/workspace/yolact/train.py", line 161, in scatter
    splits = prepare_data(inputs[0], devices, allocation=args.batch_alloc)
  File "/home/jiapy/workspace/yolact/train.py", line 432, in prepare_data
    split_images[device_idx]    = torch.stack(images[cur_idx:cur_idx+alloc], dim=0)
RuntimeError: expected a non-empty list of Tensors

**Comment by lioneldaniel** [comment]
@dzyjjpy, even if the error message is the same has mine, the traceback looks quite different, so it might be a different problem that needs a separate issue, do you agree?
@MuMuJun97, did you solve your problem that looks like mine? If yes, I could close my issue.

**Comment by dbolya** [comment]
@dzyjjpy That's an issue with batch size across different GPU's (different from the issue in this thread), so make a new issue if you haven't solved it already.

**Comment by lioneldaniel** [comment]
I close this issue because https://github.com/dbolya/yolact/issues/259#issuecomment-568178718 solved it.

**Comment by dbolya** [comment]
This is now fixed in master, you can keep discard_mask_iou on its default value.
