### ISSUE TITLE
multiprocessing error

### ISSUE THREAD

**Issue by krislp** [dbolya/yolact#267]
i want to train my model, and executed the following command:
python train.py --config=yolact_base_config
which i had executed before:
export CUDA_VISIBLE_DEVICES=0

My error message is as follows
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

**Comment by dbolya** [comment]
Uhh that's odd. Maybe try running with `--num_workers=0` or 1? The only place we use multiprocessing is internally in Pytorch for data loading.

**Comment by limse10** [comment]
I ran into the exact same issue. I was training using a coco-style dataset which was generated by combining two other coco-style datasets.

I used [datumaro](github.com/openvinotoolkit/datumaro) to combine the two datasets. 

I figured out the error was caused by conflicting/missing id's in the json. To fix it, when exporting the dataset using datumaro, i just added the --reindex=1 flag to ensure there were no conflicts. 

Super niche error and i dont think yours is caused by the same thing. But maybe this could give you some clue as to what the root of the problem is.
