### ISSUE TITLE
Error while training for custom dataset

### ISSUE THREAD

**Issue by Anonymous88988** [dbolya/yolact#272]
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 305, in train
    losses = net(datum)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "train.py", line 157, in scatter
    splits = prepare_data(inputs[0], devices, allocation=args.batch_alloc)
  File "train.py", line 410, in prepare_data
    images[cur_idx]  = gradinator(images[cur_idx].to(device))
IndexError: list index out of range

**Comment by dbolya** [comment]
What does your GPU set up and batch size look like? This can happen when you're using 4 gpus and a batch size of 1 for instance.
