### ISSUE TITLE
Train Error when running train.py as readme describe

### ISSUE THREAD

**Issue by dzyjjpy** [dbolya/yolact#279]
when I  run:
 **python train.py --config=yolact_base_config --batch_size=5**

**Had the following issue:**
Traceback (most recent call last):
  File "/home/jiapy/workspace/yolact/train.py", line 506, in <module>
    train()
  File "/home/jiapy/workspace/yolact/train.py", line 309, in train
    **losses = net(datum)**
  File "/home/jiapy/virtualEnv/py3.6torch1.0.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiapy/virtualEnv/py3.6torch1.0.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 139, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/jiapy/workspace/yolact/train.py", line 161, in scatter
    splits = prepare_data(inputs[0], devices, allocation=args.batch_alloc)
  File "/home/jiapy/workspace/yolact/train.py", line 432, in prepare_data
    split_images[device_idx]    = torch.stack(images[cur_idx:cur_idx+alloc], dim=0)
**RuntimeError: expected a non-empty list of Tensors**

And I try to modify the resnet_101 and resnet_50 backbone, it doesn't work.
I download and put resnet101  and resnet_50 model in directory /weights 
Have put /annotations(including val2017 and train2017) and /image(including val2017 and train2017) in ./data/coco/ direcrory

Besides， I  can run python eval.py successfully right now.
Looking forward to your reply. Thanks.

**Comment by dzyjjpy** [comment]
@dbolya could pls give me some advice? thanks
