### ISSUE TITLE
Yolact++ train error

### ISSUE THREAD

**Issue by enhany** [dbolya/yolact#302]
When I try to train yolact++ with my own dataset (about 1k images) with default config , I get error:

[  1]     390 || B: 3.317 | C: 2.480 | M: 7.031 | S: 0.058 | I: 5.580 | T: 18.467 || ETA: 9 days, 12:51:19 || timer: 0.628
[  1]     400 || B: 3.235 | C: 2.476 | M: 6.763 | S: 0.057 | I: 5.818 | T: 18.350 || ETA: 9 days, 12:31:34 || timer: 0.603
[  1]     410 || B: 3.171 | C: 2.472 | M: 6.627 | S: 0.059 | I: 5.943 | T: 18.271 || ETA: 9 days, 12:13:25 || timer: 0.605
[  1]     420 || B: 3.057 | C: 2.415 | M: 5.709 | S: 0.055 | I: 6.152 | T: 17.388 || ETA: 9 days, 11:56:13 || timer: 0.610

Traceback (most recent call last):
  File "train.py", line 502, in <module>
    train()
  File "train.py", line 305, in train
    losses = net(datum)
  File "d:\env\yolact\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\env\yolact\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "d:\env\yolact\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 144, in forward
    losses = self.criterion(self.net, preds, targets, masks, num_crowds)
  File "d:\env\yolact\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "Z:\files\yolact\layers\modules\multibox_loss.py", line 159, in forward
    ret = self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, score_data, inst_data, labels)
  File "Z:\files\yolact\layers\modules\multibox_loss.py", line 656, in lincomb_mask_loss
    maskiou_t = torch.cat(maskiou_t_list)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]

**Comment by dbolya** [comment]
Ah, I now realize why this is happening. @chongzhou96 didn't account for `cfg.discard_mask_area` discarding every mask in the batch. I'll have to do a bit of refactoring to fix this. For now, if you set `discard_mask_area` in the config you're using to 0, does it work?

**Comment by dbolya** [comment]
Ok the fix was easier than expected. I tested this and it worked, so you can keep `discard_mask_area` the same, just pull the fix.
