### ISSUE TITLE
eval.py issue

### ISSUE THREAD

**Issue by uni23** [dbolya/yolact#311]
When I try to use following command on anaconda prompt, it does not work well.
What's the problem?
* python eval.py --trained_model=weights/yolact_base_54_800000.pth

I installed python 3.7.3, CUDA 10.2, cuDNN 7.3.0 (to suit my environment), anaconda.
Also git Bash to download COCO dataset. 

I followed installation on this website correctly (I guess), 
to "sh data/scripts/COCO_test.sh" sentence. (There was no error)

However if I try to execute eval.py, there is error : 

==========================================================

(base) C:\Users\Ai\yolactNew\yolact>python eval.py --trained_model=weights/yolact_base_54_800000.pth
Config not specified. Parsed yolact_base_config from the file name.

loading annotations into memory...
Done (t=1.11s)
creating index...
index created!
Loading model... Done.

Traceback (most recent call last):
  File "eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "eval.py", line 949, in evaluate
    preds = net(batch)
  File "C:\Users\Ai\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Ai\yolactNew\yolact\yolact.py", line 676, in forward
    return self.detect(pred_outs, self)
  File "C:\Users\Ai\yolactNew\yolact\layers\functions\detection.py", line 71, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "C:\Users\Ai\yolactNew\yolact\layers\functions\detection.py", line 101, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "C:\Users\Ai\yolactNew\yolact\layers\functions\detection.py", line 149, in fast_nms
    iou.triu_(diagonal=1)
RuntimeError: invalid argument 1: expected a matrix at c:\a\w\1\s\tmp_conda_3.7_061434\conda\conda-bld\pytorch_1544163540495\work\aten\src\thc\generic/THCTensorMathPairwise.cu:203

**Comment by dbolya** [comment]
Your pytorch version is not high enough (you have version 1.0.0 judging by that error, while 1.0.1 is the minimum version required). Did you install the requirements through the `environment.yml` or is this your own environment?

You should be able to fix this by simply updating Pytorch.
