### ISSUE TITLE
error for evaluating my model after training on custom dataset

### ISSUE THREAD

**Issue by hana9090** [dbolya/yolact#385]
I have a dataset of 10 images for two classes and it is in coco formate. So I train the model on this ddataset and intrupt the training after 713 epoch. 

So when I try to eval an image using 

>  python eval.py --trained_model=weights/yolact_base_713_1427_interrupt.pth  --config=yolact_base_config  --images=in:out  --cuda True

Although it saved the model without issuing any error after training, I got this error when executing eval:

````
Loading model...Traceback (most recent call last):
  File "eval.py", line 1109, in <module>
    net.load_weights(args.trained_model)

  File "~/yolact/yolact.py", line 490, in load_weights
    self.load_state_dict(state_dict)

  File "~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))

RuntimeError: Error(s) in loading state_dict for Yolact:
        size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([9, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([12, 256, 3, 3]).

        size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([12]).

        size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([2, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).

        size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).
`
```

**Comment by manyaafonso** [comment]
@hana9090 did you solve this issue? Are you willing to share how?
