### ISSUE TITLE
Issue while running eval.py scripts

### ISSUE THREAD

**Issue by VibAltekar** [dbolya/yolact#4]
I am running this on a linux 18.04 box with python3 and all the most recent versions of the libraries. Any Idea why I get this error?

$ python3 eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.3 --top_k=100 --video=/home/vib/Desktop/AndurilSRC/LPR_DATA/lotsofcars_1.mp4:output_video-det.mp4

Config not specified. Parsed yolact_base_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 935, in <module>
    evaluate(net, dataset)
  File "eval.py", line 722, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 682, in savevideo
    preds = net(batch)
  File "/home/vib/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vib/Desktop/Personal/yolact/yolact.py", line 612, in forward
    return self.detect(pred_outs)
  File "/home/vib/Desktop/Personal/yolact/layers/functions/detection.py", line 76, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/vib/Desktop/Personal/yolact/layers/functions/detection.py", line 103, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/vib/Desktop/Personal/yolact/layers/functions/detection.py", line 148, in fast_nms
    iou.triu_(diagonal=1)
RuntimeError: invalid argument 1: expected a matrix at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:203
FAIL

**Comment by dbolya** [comment]
The batched `trui` operation was only added in Pytorch 1.0.1 (it's not in Pytorch 1.0.0), so please make sure you're on Pytorch 1.0.1.

**Comment by VibAltekar** [comment]
Worked like a charm! Thanks!

**Comment by mvcaro** [comment]
@dbolya what alterations can be made to replace so that it can run on Pytorch 1.0.0?

**Comment by dbolya** [comment]
@mvcaro Fast NMS requires batched `trui_`, which was added to the pytorch C++ backend in 1.0.1. There is no work around for Fast NMS that wouldn't be significantly slower.

If you really can't upgrade, you can try `--fast_nms=False` which will use traditional NMS (~10 fps slower but ~1 mAP better).
