### ISSUE TITLE
There was a problem compiling DCNv2

### ISSUE THREAD

**Issue by zhaoliu5254** [dbolya/yolact#405]
My configuration：pytorch 1.4.0  and py3.7_cuda10.1.243_cudnn7.6.3_0.
Train and evaluate YOLACT everything works.
I want to use YOLACT ++, but I have a problem compiling DCN：
python setup.py build develop
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel
Thanks!

**Comment by zjwson** [comment]
you hava resolved this problem?

**Comment by zhaoliu5254** [comment]
Hello, export CUDA_HOME = "your CUDA path" can solve my problem: 
NotImplementedError: Cuda is not availabel. 
After successfully running python setup.py build develop, and then using YOLACT ++, there will still be new problems: 
Exception: DCN could not be imported. If you want to use YOLACT ++ models, compile DCN. Check the README for instructions.

**Comment by zjwson** [comment]
I tried this way according what you said, but it didn't work. I think it could be the reason that my driver is too old to work.

**Comment by studentWUR** [comment]
I also had some problems with DCN despite the succesfully running setup.py Try to remove old build and then rebuild and test again.

`rm -r build`
`python setup.py develop`
