### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1]

### ISSUE THREAD

**Issue by tunghustvn** [dbolya/yolact#425]
Hi, thanks for your great contribution.
I have a problem while training with custom dataset. When the model calculate the validation mAP, an error occur like below, anyone knows how to fix it?
Thanks.
```
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 371, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 492, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/hanguyen/Tung_yolact/yolact/eval.py", line 956, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/hanguyen/Tung_yolact/yolact/eval.py", line 435, in prep_metrics
    mask_iou_cache = _mask_iou(masks, gt_masks)
  File "/home/hanguyen/Tung_yolact/yolact/eval.py", line 378, in _mask_iou
    ret = mask_iou(mask1, mask2, iscrowd)
  File "/home/hanguyen/Tung_yolact/yolact/layers/box_utils.py", line 108, in mask_iou
    masks_b = masks_b.view(masks_b.size(0), -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguo$
s
```

**Comment by tunghustvn** [comment]
The reason of this error is my data. I don't know why but I just skipped the error elements and it worked.

**Comment by davodogster** [comment]
I had the same problem. I removed iscrowd = 1 in the .json and it fixed it
