### ISSUE TITLE
KeyError: 'I'

### ISSUE THREAD

**Issue by AlexFridman** [dbolya/yolact#442]
Hi! I'm trying to fine-tune on 2GPU machine and getting the following error:

```
(jupyter) ubuntu@mash:~/Documents/repos/yolact$ python train.py --config=yolact_plus_resnet50_config  --validation_epoch=1 --validation_size=800 --batch_size 4 --resume
~/Downloads/yolact_plus_resnet50_462_820000.pth
Multiple GPUs detected! Turning off JIT.
Scaling parameters by 0.50 to account for a batch size of 4.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=74.50s)
creating index...
index created!
loading annotations into memory...
Done (t=3.23s)
creating index...
index created!
Resuming training, loading /home/ubuntu/Downloads/yolact_plus_resnet50_462_820000.pth...
Begin training!

[203]  820000 || B: 3.965 | C: 2.830 | M: 4.478 | S: 0.351 | I: 0.345 | T: 11.970 || ETA: 0:00:00 || timer: 12.324
[203]  820010 || B: 3.750 | C: 2.804 | M: 4.354 | S: 0.293 | I: 0.380 | T: 11.582 || ETA: 14 days, 2:32:01 || timer: 0.829
[203]  820020 || B: 3.685 | C: 2.763 | M: 4.082 | S: 0.289 | I: 0.390 | T: 11.209 || ETA: 18 days, 10:59:32 || timer: 2.691
[203]  820030 || B: 3.531 | C: 2.710 | M: 4.017 | S: 0.306 | I: 0.309 | T: 10.873 || ETA: 26 days, 0:32:25 || timer: 0.744
[203]  820040 || B: 3.423 | C: 2.674 | M: 3.775 | S: 0.314 | I: 0.275 | T: 10.460 || ETA: 22 days, 20:44:42 || timer: 0.534
[203]  820050 || B: 3.344 | C: 2.642 | M: 3.752 | S: 0.301 | T: 10.040 || ETA: 21 days, 11:16:28 || timer: 1.381
[203]  820060 || B: 3.289 | C: 2.618 | M: 3.725 | S: 0.290 | I: 0.233 | T: 10.155 || ETA: 20 days, 13:28:29 || timer: 0.742
[203]  820070 || B: 3.258 | C: 2.599 | M: 3.719 | S: 0.290 | I: 0.218 | T: 10.085 || ETA: 19 days, 22:55:59 || timer: 0.522
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 307, in train
    losses = net(datum)
  File "/home/ubuntu/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "train.py", line 168, in gather
    out[k] = torch.stack([output[k].to(output_device) for output in outputs])
  File "train.py", line 168, in <listcomp>
    out[k] = torch.stack([output[k].to(output_device) for output in outputs])
KeyError: 'I'
```

Any help appreciated. Thank you!

**Comment by pieterbl86** [comment]
> Hi! I'm trying to fine-tune on 2GPU machine and getting the following error:
> In a single GPU mode on the same machine, it works like a charm (`CUDA_VISIBLE_DEVICES=1 python train.py --config=yolact_plus_resnet50_config --validation_epo ..`)
> 
> ```
> (jupyter) ubuntu@mash:~/Documents/repos/yolact$ python train.py --config=yolact_plus_resnet50_config  --validation_epoch=1 --validation_size=800 --batch_size 4 --resume
> ~/Downloads/yolact_plus_resnet50_462_820000.pth
> Multiple GPUs detected! Turning off JIT.
> Scaling parameters by 0.50 to account for a batch size of 4.
> Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
> loading annotations into memory...
> Done (t=74.50s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=3.23s)
> creating index...
> index created!
> Resuming training, loading /home/ubuntu/Downloads/yolact_plus_resnet50_462_820000.pth...
> Begin training!
> 
> [203]  820000 || B: 3.965 | C: 2.830 | M: 4.478 | S: 0.351 | I: 0.345 | T: 11.970 || ETA: 0:00:00 || timer: 12.324
> [203]  820010 || B: 3.750 | C: 2.804 | M: 4.354 | S: 0.293 | I: 0.380 | T: 11.582 || ETA: 14 days, 2:32:01 || timer: 0.829
> [203]  820020 || B: 3.685 | C: 2.763 | M: 4.082 | S: 0.289 | I: 0.390 | T: 11.209 || ETA: 18 days, 10:59:32 || timer: 2.691
> [203]  820030 || B: 3.531 | C: 2.710 | M: 4.017 | S: 0.306 | I: 0.309 | T: 10.873 || ETA: 26 days, 0:32:25 || timer: 0.744
> [203]  820040 || B: 3.423 | C: 2.674 | M: 3.775 | S: 0.314 | I: 0.275 | T: 10.460 || ETA: 22 days, 20:44:42 || timer: 0.534
> [203]  820050 || B: 3.344 | C: 2.642 | M: 3.752 | S: 0.301 | T: 10.040 || ETA: 21 days, 11:16:28 || timer: 1.381
> [203]  820060 || B: 3.289 | C: 2.618 | M: 3.725 | S: 0.290 | I: 0.233 | T: 10.155 || ETA: 20 days, 13:28:29 || timer: 0.742
> [203]  820070 || B: 3.258 | C: 2.599 | M: 3.719 | S: 0.290 | I: 0.218 | T: 10.085 || ETA: 19 days, 22:55:59 || timer: 0.522
> Traceback (most recent call last):
>   File "train.py", line 504, in <module>
>     train()
>   File "train.py", line 307, in train
>     losses = net(datum)
>   File "/home/ubuntu/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/ubuntu/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
>     return self.gather(outputs, self.output_device)
>   File "train.py", line 168, in gather
>     out[k] = torch.stack([output[k].to(output_device) for output in outputs])
>   File "train.py", line 168, in <listcomp>
>     out[k] = torch.stack([output[k].to(output_device) for output in outputs])
> KeyError: 'I'
> ```
> 
> Any help appreciated. Thank you!

@dbolya @AlexFridman 
I have the same error. I tried to train YOLACT++ on 2 NVIDIA 2080Ti's with this command:
`export CUDA_VISIBLE_DEVICES=0,1`
`python train.py --config=yolact_plus_base_im1024_config --batch_size=4 --batch_alloc=2,2 --dataset=custom_dataset --validation_epoch=-1 --save_interval=500`

I'll try if the error resolves when training on 1 gpu:
`export CUDA_VISIBLE_DEVICES=0`
`python train.py --config=yolact_plus_base_im1024_config --batch_size=2 --dataset=custom_dataset --validation_epoch=-1 --save_interval=500`

Note that I have specified a config file for YOLACT++ (Resnet101) that processes images of 1024 pixels (as that's the same resolution of Mask R-CNN, to be able to equally compare them):

yolact_plus_base_im1024_config = yolact_plus_base_config.copy({
    'name': 'yolact_plus_base_im1024',
    'masks_to_train': 300,
    'max_size': 1024,
    'backbone': resnet101_dcn_inter3_backbone.copy({
        'selected_layers': list(range(1, 4)),
        'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
        'pred_scales': [[i * 2 ** (j / 3.0) for j in range(3)] for i in [24, 48, 96, 192, 384]],
        'use_pixel_scales': True,
        'preapply_sqrt': False,
        'use_square_anchors': False,
    }),
    'use_maskiou': True,
    'maskiou_net': [(8, 3, {'stride': 2}), (16, 3, {'stride': 2}), (32, 3, {'stride': 2}), (64, 3, {'stride': 2}), (128, 3, {'stride': 2})],
    'maskiou_alpha': 25,
    'rescore_bbox': False,
    'rescore_mask': True,
    'discard_mask_area': 5*5,
})

**Comment by SuyueLiu** [comment]
I got the same error when I tried to train YOLACT++ with multiple GPUs, and this works fine on a single GPU.
For me, this is caused by [CustomDataParallel](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/train.py#L149). In my opinion, when you use multiple GPUs, let's say 4 (named 0~3), the function `gather` will copy the results from GPU 1, 2, 3 to the GPU No. 0 to get the final result.


I have solved this error with a few steps:

**Comment by ZyrianovS** [comment]
@SuyueLiu Thanks, mate!

**Comment by antoniototimorelli** [comment]
> 
> 
> I got the same error when I tried to train YOLACT++ with multiple GPUs, and this works fine on a single GPU.
> 
> For me, this is caused by [CustomDataParallel](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/train.py#L149). In my opinion, when you use multiple GPUs, let's say 4 (named 0~3), the function `gather` will copy the results from GPU 1, 2, 3 to the GPU No. 0 to get the final result. If there is an image that has no object that we are interested in or the RoI is too small to be considered by the model, the loss of that part is None, that why there is no key "I".
> 
> I have two pieces of suggestions for this problem:
> 
>     1. The first method, you can decrease the resolution of [discard_mask_area](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/data/config.py#L791).
> 
>     2. The second method is giving zero loss when the `maskiou_targets` is None in [moltibox_loss.py](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/layers/modules/multibox_loss.py#L187), say my [repo](https://github.com/SuyueLiu/yolact/blob/565d154656f9d80b584344399b7fbf73d3c26009/layers/modules/multibox_loss.py#L187) for details.
> 
> 
> I tried the second one and it has worked.

Hi, is it possible that your second suggestion leads to another type of error?
```
Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box |  0.00 |  0.01 |  0.01 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
  mask |  0.01 |  0.05 |  0.03 |  0.02 |  0.01 |  0.01 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+

[ 16]     470 || B: 164318362760289312.000 | C: 140699302322624128.000 | M: 17.014 | S: 11.839 | I: 0.731 | T: 305017665082913472.000 || ETA: 23:59:53 || timer: 0.791
Saving state, iter: 470
[ 16]     480 || B: 164318362760294944.000 | C: 140699302322628544.000 | M: 17.585 | S: 12.220 | I: 0.695 | T: 305017665082923520.000 || ETA: 23:50:14 || timer: 27.088
Saving state, iter: 480
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
[ 16]     490 || B: 164318362760294944.000 | C: 140699302322628544.000 | M: 18.213 | S: 12.592 | I: 0.596 | T: 305017665082923520.000 || ETA: 23:38:41 || timer: 28.417
Saving state, iter: 490

Computing validation mAP (this may take a while)...


Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
  mask |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
```
After some iterations, i get those enormous loss values and mAP sets to 0. Have you encountered this error or got any idea in how to fix this?
