### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2

### ISSUE THREAD

**Issue by wdkwyf** [dbolya/yolact#465]
Hi, anyone convert yolact_plus to ONNX successfully?

**Comment by biyuehuang** [comment]
No, I still try. But I convert yolact to onnx sucessfully by https://zhuanlan.zhihu.com/p/128974102. Then I modify eval.py to convert yolact_plus
```
import DCNv2
def evalimage(net:Yolact, path:str, save_path:str=None):
    frame = torch.from_numpy(cv2.imread(path)).float()
    batch = FastBaseTransform()(frame.unsqueeze(0))
    preds = net(batch)
    torch.onnx.export(net, batch, "yolact_plus.onnx",operator_export_type=DCNv2)
```
$ python3 eval.py --trained_model=/home/kiwi/Document/yolact/data/models/yolact_plus_base_54_800000.pth --score_threshold=0.3 --top_k=10 --image=dog.jpg --cuda=False

Error:
Multiple GPUs detected! Turning off JIT.
Config not specified. Parsed yolact_plus_base_config from the file name.

Loading model... Done.
/home/kiwi/Document/yolact/DCNv2/dcn_v2.py:31: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ctx.deformable_groups)
/home/kiwi/Document/yolact/yolact.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):
Traceback (most recent call last):
  File "eval.py", line 1123, in <module>
    evaluate(net, dataset)
  File "eval.py", line 895, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 609, in evalimage
    torch.onnx.export(net, batch, "yolact_plus.onnx",operator_export_type=DCNv2)
  File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph

**Comment by hyperfraise** [comment]
I'm very interested in this. Got the same error.

**Comment by mrljwlm** [comment]
the same problem

**Comment by myl353** [comment]
@biyuehuang  Excuse me, have you solved this problem? I'm got the same error...

**Comment by biyuehuang** [comment]
Update. I can convert yolact to ONNX refer to https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_pytorch_specific_Convert_YOLACT.html

But yolact++ still have error.
python eval.py --trained_model=./data/models/yolact_plus_base_54_800000.pth --score_threshold=0.3 --top_k=10 --image=./d.jpg

> Config not specified. Parsed yolact_plus_base_config from the file name.
> 
> Loading model... Done.
> /home/kiwi/Document/yolact/external/DCNv2/dcn_v2.py:31: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   ctx.deformable_groups)
> /home/kiwi/Document/yolact/yolact.py:223: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):
> /home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py:246: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
> ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
> We recommend using opset 11 and above for models using this operator.
>   "" + str(_export_onnx_opset_version) + ". "
> Traceback (most recent call last):
>   File "eval.py", line 1108, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 884, in evaluate
>     evalimage(net, args.image)
>   File "eval.py", line 602, in evalimage
>     torch.onnx.export(net, batch, "yolact_plus.onnx")
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
>     strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
>     dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 428, in _export
>     operator_export_type, strip_doc_string, val_keep_init_as_ip)
> RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2
