### ISSUE TITLE
I cann't compile compile the DCNv2 (Windows)

### ISSUE THREAD

**Issue by yuyonod** [dbolya/yolact#466]
I want to test the yolact++, but I cann't compile DCNv2. My enviroment is as follow:
OS: Windows10
cuda: 11.0
python: 3.7.0
pytorch:1.5.0
When I compiled the DCNv2 I found the following errors:

I've also checked the issue which looks similar to me, but I couldnt find solution.
Is this problem because of cuda verision is too latest(11.0) ?
Anyone help me please? Thank you in advance.

`yolact-env) C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2>python setup.py build develop
which: no hipcc in (/c/Users/layer/anaconda3/envs/yolact-env/lib/site-packages/torch/lib:/bin:/c/Users/layer/anaconda3/envs/yolact-env:/mingw-w64/bin:/usr/bin:/bin:/c/Users/layer/anaconda3/envs/yolact-env/Scripts:/c/Users/layer/anaconda3/envs/yolact-env/bin:/c/Users/layer/anaconda3/condabin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/libnvvp:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Git/cmd:/c/Program Files/NVIDIA 
Corporation/Nsight Compute 2020.1.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Users/layer/AppData/Local/Microsoft/WindowsApps:.:/c/Users/layer/AppData/Local/Programs/Microsoft VS Code/bin)
running build
running build_ext
C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] 指定されたファイルが見つかりません。   
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building '_ext' extension
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cpu
creating C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cuda
Emitting ninja build file C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/5] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\TH -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\layer\anaconda3\envs\yolact-env\include -IC:\Users\layer\anaconda3\envs\yolact-env\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows 
Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\vision.cpp /FoC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/layer/Desktop/work/yolact-master/yolact/external/DCNv2/build/temp.win-amd64-3.7/Release/Users/layer/Desktop/work/yolact-master/yolact/external/DCNv2/src/vision.obj 
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\TH -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\layer\anaconda3\envs\yolact-env\include -IC:\Users\layer\anaconda3\envs\yolact-env\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\vision.cpp /FoC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/5] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\TH -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\layer\anaconda3\envs\yolact-env\include -IC:\Users\layer\anaconda3\envs\yolact-env\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows 
Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cpu\dcn_v2_cpu.cpp /FoC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cpu\dcn_v2_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/layer/Desktop/work/yolact-master/yolact/external/DCNv2/build/temp.win-amd64-3.7/Release/Users/layer/Desktop/work/yolact-master/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.obj 
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\TH -IC:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\layer\anaconda3\envs\yolact-env\include -IC:\Users\layer\anaconda3\envs\yolact-env\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cpu\dcn_v2_cpu.cpp /FoC:\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\build\temp.win-amd64-3.7\Release\Users\layer\Desktop\work\yolact-master\yolact\external\DCNv2\src\cpu\dcn_v2_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: ハンドルが無効です。

Traceback (most recent call last):
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\setuptools\__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\layer\anaconda3\envs\yolact-env\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension`

**Comment by sabine1993** [comment]
I have the same problem. Did you find a solution?

**Comment by PNeigel** [comment]
Same problem here

**Comment by PNeigel** [comment]
Actually it also happens on Ubuntu 18.04.02

**Comment by JunnYu** [comment]
Fixes for Pytorch 1.6 and CUDA 11 https://github.com/CharlesShang/DCNv2/pull/71
add pytorch 1.5 supported https://github.com/CharlesShang/DCNv2/pull/58
