### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Yolact: when train on custom dataset

### ISSUE THREAD

**Issue by minhtcai** [dbolya/yolact#467]
Hi, I was trying to train on my custom dataset and get this error, I barely used pytorch before so I have no idea how to fix it, really appreciate your help, thank you!

**Command:**

python train.py --config=dataset_base --resume=weights/resnet101_reducedfc.pth --dataset=base_dataset

**Error:**
Multiple GPUs detected! Turning off JIT.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Resuming training, loading weights/resnet101_reducedfc.pth...
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 207, in train
    yolact_net.load_weights(args.resume)
  File "/home/ubuntu/yolact/yolact.py", line 490, in load_weights
    self.load_state_dict(state_dict)
  File "/home/ubuntu/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
	Missing key(s) in state_dict: "backbone.layers.0.0.conv1.weight", "backbone.layers.0.0.bn1.weight", "backbone.layers.0.0.bn1.bias", "backbone.layers.0.0.bn1.running_mean", "backbone.layers.0.0.bn1.running_var", "backbone.layers.0.0.conv2.weight", "backbone.layers.0.0.bn2.weight", "backbone.layers.0.0.bn2.bias", "backbone.layers.0.0.bn2.running_mean", "backbone.layers.0.0.bn2.running_var", "backbone.layers.0.0.conv3.weight"

**Comment by Ru-Van** [comment]
The same error. @minhtcai Did you fix the problem?

**Comment by minhtcai** [comment]
I forgot how I fixed it. but check the config file and the weights carefully, these have to be matched.

**Comment by rohanshingade** [comment]
I'm getting the same error. Any idea how to fix this. Converted the code for CPU usage and trying to do evaluation with yolact++ resnet 101 weights.


```
RuntimeError: Error(s) in loading state_dict for Yolact:
	Unexpected key(s) in state_dict: "backbone.layers.1.0.conv2.bias", "backbone.layers.1.0.conv2.conv_offset_mask.weight", "backbone.layers.1.0.conv2.conv_offset_mask.bias", "backbone.layers.1.3.conv2.bias", "backbone.layers.1.3.conv2.conv_offset_mask.weight", "backbone.layers.1.3.conv2.conv_offset_mask.bias", "backbone.layers.2.0.conv2.bias", "backbone.layers.2.0.conv2.conv_offset_mask.weight", "backbone.layers.2.0.conv2.conv_offset_mask.bias", "backbone.layers.2.3.conv2.bias", "backbone.layers.2.3.conv2.conv_offset_mask.weight", "backbone.layers.2.3.conv2.conv_offset_mask.bias", "backbone.layers.2.6.conv2.bias", "backbone.layers.2.6.conv2.conv_offset_mask.weight", "backbone.layers.2.6.conv2.conv_offset_mask.bias", "backbone.layers.2.9.conv2.bias", "backbone.layers.2.9.conv2.conv_offset_mask.weight", "backbone.layers.2.9.conv2.conv_offset_mask.bias", "backbone.layers.2.12.conv2.bias", "backbone.layers.2.12.conv2.conv_offset_mask.weight", "backbone.layers.2.12.conv2.conv_offset_mask.bias", "backbone.layers.2.15.conv2.bias", "backbone.layers.2.15.conv2.conv_offset_mask.weight", "backbone.layers.2.15.conv2.conv_offset_mask.bias", "backbone.layers.2.18.conv2.bias", "backbone.layers.2.18.conv2.conv_offset_mask.weight", "backbone.layers.2.18.conv2.conv_offset_mask.bias", "backbone.layers.2.21.conv2.bias", "backbone.layers.2.21.conv2.conv_offset_mask.weight", "backbone.layers.2.21.conv2.conv_offset_mask.bias", "backbone.layers.3.0.conv2.bias", "backbone.layers.3.0.conv2.conv_offset_mask.weight", "backbone.layers.3.0.conv2.conv_offset_mask.bias". 

```

**Comment by chethanningappa** [comment]
set the directly to yoloact worked for me..
