### ISSUE TITLE
YOLACT ++: RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by sabine1993** [dbolya/yolact#475]
Hi there,
I try to use Yolact++ and I already installed the additional setup.py file and I didn't get an error during the installation. The normal yolact configuration works without problems. 
When I am trying to run yolact++ with the config file I get the following error fpr the maskiou list.
Does someone have an Idea what is going wrong?

Thanks a lot

Traceback (most recent call last):
  File "train.py", line 520, in <module>
    train()
  File "train.py", line 309, in train
    losses = net(datum)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 145, in forward
    losses = self.criterion(self.net, preds, targets, masks, num_crowds)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\skugler\Desktop\Sabine_master\yolact\layers\modules\multibox_loss.py", line 159, in forward
    ret = self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, score_data, inst_data, labels)
  File "C:\Users\skugler\Desktop\Sabine_master\yolact\layers\modules\multibox_loss.py", line 662, in lincomb_mask_loss
    maskiou_t = torch.cat(maskiou_t_list)
RuntimeError: expected a non-empty list of Tensors

**Comment by Nerdyvedi** [comment]
@sabine1993 I am getting the same error. How were you able to fix this problem ?

**Comment by naeunhub** [comment]
Did you fix it?
