### ISSUE TITLE
Training with empty segmentation masks

### ISSUE THREAD

**Issue by sabine1993** [dbolya/yolact#489]
Hi everyone,
does any one know if there is a possibility to train yolact with partly empty segmentation masks?
I don't have a mask for specific classes but I want to train one model.
I tried using segmentation=[] but I am running into an error during training.

  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\skugler\Desktop\Sabine_master\yolact\data\coco.py", line 95, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "C:\Users\skugler\Desktop\Sabine_master\yolact\data\coco.py", line 154, in pull_item
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "C:\Users\skugler\Desktop\Sabine_master\yolact\data\coco.py", line 154, in <listcomp>
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\pycocotools\coco.py", line 431, in annToMask
    rle = self.annToRLE(ann)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_yolact\lib\site-packages\pycocotools\coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools\_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

Has anyone solved this problem or has an idea how to solve it?

**Comment by DozieSixtus** [comment]
I just encountered this issue. Any solutions yet?

**Comment by DozieSixtus** [comment]
> I've meet the same issue

Have you been able to solve it?
