### ISSUE TITLE
Training on custom dataset index error

### ISSUE THREAD

**Issue by pentadotddot** [dbolya/yolact#494]
Hi!

I am trying to train on a custom dataset and I get this error:

python train.py --config=yolact_base_config --resume=weights/resnet101_reducedfc.pth --start_iter=-1  --validation_size 21 --validation_epoch 10 

loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:165: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:165: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/jit/_recursive.py:165: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 187, in train
    yolact_net = Yolact()
  File "/mnt/meganeura/domeemod/yolact/yolact.py", line 467, in __init__
    self.semantic_seg_conv = nn.Conv2d(src_channels[0], cfg.num_classes-1, kernel_size=1)
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 408, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 83, in __init__
    self.reset_parameters()
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 86, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/init.py", line 381, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/init.py", line 350, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/scratch/domeemod/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/init.py", line 282, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

I have a dataset with which I have already trained a detectron2 mask-rcnn model, thus I am not really suspicious about the correctness of my dataset and annotations.

my custom config.py file:

dataset_base = Config({
    'name': 'Grapes Dataset',

    # Training images and annotations
    'train_images': './grapeNation/train/',
    'train_info':   './grapeNation/train.json',

    # Validation images and annotations.
    'valid_images': './grapeNation/test/',
    'valid_info':   './grapeNation/test.json',

    # Whether or not to load GT. If this is False, eval.py quantitative evaluation won't work.
    'has_gt': True,

    # A list of names for each of you classes.
    'class_names': custom_classes ,

    # COCO class ids aren't sequential, so this is a bandage fix. If your ids aren't sequential,
    # provide a map from category_id -> index in class_names + 1 (the +1 is there because it's 1-indexed).
    # If not specified, this just assumes category ids start at 1 and increase sequentially.
    'label_map': None
})

grapes_dataset = dataset_base.copy({
    'name': 'Grapes Dataset',

    # Training images and annotations
    'train_images': './grapeNation/train/',
    'train_info':   './grapeNation/train.json',

    # Validation images and annotations.
    'valid_images': './grapeNation/test/',
    'valid_info':   './grapeNation/test.json',

    # Whether or not to load GT. If this is False, eval.py quantitative evaluation won't work.
    'has_gt': True,

    # A list of names for each of you classes.
    'class_names': custom_classes ,

    # COCO class ids aren't sequential, so this is a bandage fix. If your ids aren't sequential,
    # provide a map from category_id -> index in class_names + 1 (the +1 is there because it's 1-indexed).
    # If not specified, this just assumes category ids start at 1 and increase sequentially.
    'label_map': None
})

Thank you in advance!

**Comment by pentadotddot** [comment]
Ok I figured it out: num_classes in config.py has to be at least 2 (including background)
