### ISSUE TITLE
eval.py raising error when trying to use the custom-trained weights

### ISSUE THREAD

**Issue by DigitalPlantScience** [dbolya/yolact#501]
I got this error. Any idea what this is about? 

I used yolact, not yolact ++. It's weird that the weight file saved with name "yolact_plus", instead of just "yolact".

`!python eval.py --trained_model=./weights/yolact_plus_resnet50_cottweeds_8_287_interrupt.pth --config=yolact_resnet50_cottweeds_config --score_threshold=0.3 --top_k=15 --images=test_images:output_images`

Loading model...Traceback (most recent call last):
  File "eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/home/ubuntu/anaconda3/yolact/yolact.py", line 479, in load_weights
    state_dict = torch.load(path)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 434506 more bytes. The file might be corrupted.
Segmentation fault (core dumped)

**Comment by ws312** [comment]
I met the same situation, have you solved it?
