### ISSUE TITLE
Segmentation fault when training with multi gpus

### ISSUE THREAD

**Issue by a2394797795** [dbolya/yolact#54]
When I train this model on a single gpu everything is ok, but I met some problems while training with multi gpus.
This dose not happen frequently, but it would eventually appear if training for a long time.
Dose anyone meet the same problem or just there's something wrong with me?
Thanks a lot.

`Traceback (most recent call last):
  File "train.py", line 342, in <module>
    train()
  File "train.py", line 244, in train
    out = net(images)
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/wzt/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wzt/project/yolact-master/yolact.py", line 535, in forward
    outs = self.backbone(x)
  File "/home/wzt/project/yolact-master/utils/timer.py", line 115, in __exit__
    stop(self.fn_name, use_stack=self.use_stack)
  File "/home/wzt/project/yolact-master/utils/timer.py", line 57, in stop
    _running_timer = _timer_stack.pop()
IndexError: pop from empty list
Segmentation fault (core dumped)
`

**Comment by dbolya** [comment]
Weird. It looks like you're having a race condition with the timer that I'm using. Since I don't use that timer during training anyway, I've added something to disable it then.

Let me know if this happens again on the latest commit.

**Comment by a2394797795** [comment]
I've tried again with the latest code version, it seems this problem has been fixed.
Thank you for your patience.

**Comment by dbolya** [comment]
Glad to hear!
