### ISSUE TITLE
cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:416

### ISSUE THREAD

**Issue by kalanityL** [dbolya/yolact#565]
Hi, 

I have no worry running YOLACT (thank you  for that 👍 )
Thank you for the code and the pretrained models, great work! 

But I have issue when it comes to YOLAC_PLUS. I compiled successfully DCNv2
I am running YOLACT inside a docker container, and I encounter this error. Do you have any idea what might cause that issue ? 

Here is the full trace and error, followed by the environment. 

**Trace :** 

```
$python3 eval.py --config=yolact_plus_resnet50_config --trained_model=weights/yolact_plus_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --images=INPUTS:OUTPUTSplus
Loading model... Done.
will begin evaluate

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "eval.py", line 1112, in <module>
    evaluate(net, dataset)
  File "eval.py", line 892, in evaluate
    evalimages(net, inp, out)
  File "eval.py", line 629, in evalimages
    evalimage(net, path, out_path)
  File "eval.py", line 604, in evalimage
    preds = net(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/root/home/kalanityL/YolactPPFork/yolact.py", line 571, in forward
    outs = self.backbone(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/root/home/kalanityL/YolactPPFork/backbone.py", line 136, in forward
    x = layer(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/root/home/kalanityL/YolactPPFork/backbone.py", line 44, in forward
    out = self.conv2(out)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/root/home/kalanityL/YolactPPFork/external/DCNv2/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/workspace/root/home/kalanityL/YolactPPFork/external/DCNv2/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:416
```

**Configuration :** 
Thank you for the code and the pretrained modeles, great work! 
K. 
```
$python3 --version
Python 3.5.2


$pip3 list
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package         Version  Location
--------------- -------- -----------------------------------------------------
cycler          0.10.0
Cython          0.29.21
DCNv2           0.1      /workspace/root/home/kalanityL/YolactPPFork/external/DCNv2
kiwisolver      1.1.0
matplotlib      3.0.3
numpy           1.18.5
opencv-python   4.4.0.42
Pillow          7.2.0
pip             20.2.4
pycocotools     2.0.2
pyparsing       2.4.7
python-dateutil 2.8.1
setuptools      20.7.0
six             1.15.0
torch           1.0.1
torchvision     0.2.2
tqdm            4.19.9
wheel           0.29.0


$cat /etc/os-release 

NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial


$nvidia-smi 
Sat Nov 14 07:56:51 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$cat /usr/local/cuda-10.0/version.txt 
CUDA Version 10.0.130

```

I am struggling for a while, would be glad if someone could help. 
Thanks :)

**Comment by overman1** [comment]
I have the same issue 
while train by yolact_plus_resnet50_config  or yolact_plus_base_config

**Comment by Aykatia** [comment]
I have the same issue. Did found a solution ?
