### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Yolact:         size mismatch for prediction_layers.0.conf_layer.weight:

### ISSUE THREAD

**Issue by DEncounter** [dbolya/yolact#577]
Scaling parameters by 0.50 to account for a batch size of 4.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Resuming training, loading weights/yolact_base_54_800000.pth...
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 207, in train
    yolact_net.load_weights(args.resume)
  File "/home/md/PycharmProjects/yolact-master/yolact.py", line 494, in load_weights
    self.load_state_dict(state_dict)
  File "/home/md/anaconda3/envs/pytorch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
        size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([243, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 256, 3, 3]).
        size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([243]) from checkpoint, the shape in current model is torch.Size([6]).
        size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 256, 1, 1]).
        size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).

**Comment by NTS-wen** [comment]
i have the same question.

**Comment by qingweihk** [comment]
i have the same question.

**Comment by overman1** [comment]
i have the same question to use pretrained model

**Comment by NTS-wen** [comment]
You can fine the issue with the title of "Fine tuning with existing model" and your question will be resolved.



At 2021-04-29 17:20:01, "overman1" ***@***.***> wrote:

i have the same question to use pretrained model
