### ISSUE TITLE
KeyError on custom dataset

### ISSUE THREAD

**Issue by JSharp4273** [dbolya/yolact#58]
Hello 

I am facing a 'new' KeyError issue.

I would like to train yolact on a custom dataset.
For that I prepared the json files and the dataset as follow:
```
PICO_LILA_CLASSES = ('back_left_leg', 'back_right_leg', 'chains',
 'front_left_leg', 'front_right_leg', 'left_ear', 'right_ear', 'left_eye',
 'right_eye', 'left_side', 'right_side', 'nose', 'rectum', 'vagina')

PICO_LILA_LABEL_MAP = {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9,
 10: 10, 11: 11, 12: 12, 13: 13, 14: 14}

picolila_dataset = dataset_base.copy({
    'name': 'PICO LILA',
    
    'train_images':'/media/smile/b5d1b325-9252-4187-a890-4caf54255c8a/pico/cow/gt/cow_relabeled_light/JPEGImages',
    'train_info':'/media/smile/b5d1b325-9252-4187-a890-4caf54255c8a/pico/cow/gt/cow_relabeled_light/train.json',

    'valid_images':'/media/smile/b5d1b325-9252-4187-a890-4caf54255c8a/pico/cow/gt/cow_relabeled_light/JPEGImages',
    'valid_info':'/media/smile/b5d1b325-9252-4187-a890-4caf54255c8a/pico/cow/gt/cow_relabeled_light/val.json',

    'label_map': PICO_LILA_LABEL_MAP,
    'class_names': PICO_LILA_CLASSES,
})
```
Then I setup the fields `dataset` and `num_classes` in `coco_base_config`
```

    'dataset': picolila_dataset,
    'num_classes': len(picolila_dataset.class_names) + 1,
```

Now when I start the training is the error:

```
%run train.py --config=yolact_base_config
loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
loading annotations into memory...
Done (t=0.57s)
creating index...
index created!
Initializing weights...
NB CLASSES: 15
NB IMAGES TO LOAD: 403
Begin training!

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/hdd1/prog/yolact/train.py in <module>()
    475 
    476 
--> 477             for datum in data_loader:
    478 
    479                 #print(type(datum), len(datum), type(datum[0]), type(datum[1]))

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

KeyError: 'Traceback (most recent call last):\n  File "/home/smile/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/smile/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/hdd1/prog/yolact/data/coco.py", line 90, in __getitem__\n    im, gt, masks, h, w, num_crowds = self.pull_item(index)\n  File "/hdd1/prog/yolact/data/coco.py", line 147, in pull_item\n    target = self.target_transform(target, width, height)\n  File "/hdd1/prog/yolact/data/coco.py", line 41, in __call__\n    label_idx = self.label_map[obj[\'category_id\']] - 1\nKeyError: 0\n'

```

I tried to investigate the same way as done on #40 
I also investigate on other dataset that I know works (e.g. Pascal Voc 2012) but even with it fails if in the file:
_/hdd1/prog/yolact/data/coco.py_ I try to print: `print(self.label_map[0])`

I also investigate using `pycocotools` if my training and validations json files are correct it seems they are.
The category index corresponds to what I setup in _config.py_.

My understanding is that there is no key 0 for the attributes `label_map` of the class `COCOAnnotationTransform` because every dataset label map starts at the keys at 1.

Could this error having something to do with the fact that my dataset is in monochannel grayscale ?

**Comment by dbolya** [comment]
In your `train.json` annotations file, check all the class ids. It looks like whoever made the dataset started the class ids at 0. If you verify that all class ids in your annotations file are in the range 0-13 (inclusive), then you can fix this by simply changing the label map to `{0:1, 1:2, 2:3, ..., 13:14}`.

**Comment by JSharp4273** [comment]
Effectively the indexation of the labels was the issue.
The script used to generate the train.json file is under investigation in order to correct the issue.

Thank you very much for help.
