### ISSUE TITLE
bug in yolact when run train.py

### ISSUE THREAD

**Issue by SylvainArd** [dbolya/yolact#601]
Hello, I'm trying to execute the yolact code :
https://github.com/dbolya/yolact
but I have this bug when I run train.py:
```

runfile('C:/Users/Sylvain ARD/Dropbox/Documents Sylvain/travail avec Boubacar/yolact/yolact-master/yolact-master/train.py', wdir='C:/Users/Sylvain ARD/Dropbox/Documents Sylvain/travail avec Boubacar/yolact/yolact-master/yolact-master')
Scaling parameters by 0.12 to account for a batch size of 1.
Per-GPU batch size is less than the recommended limit for batch norm. Disabling batch norm.
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):

  File "C:\Users\Sylvain ARD\Dropbox\Documents Sylvain\travail avec Boubacar\yolact\yolact-master\yolact-master\train.py", line 505, in <module>
    train()

  File "C:\Users\Sylvain ARD\Dropbox\Documents Sylvain\travail avec Boubacar\yolact\yolact-master\yolact-master\train.py", line 271, in train
    for datum in data_loader:

  File "C:\Users\Sylvain ARD\.conda\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)

  File "C:\Users\Sylvain ARD\.conda\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()

  File "C:\Users\Sylvain ARD\.conda\envs\yolact\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)

TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

```

please help me
thank you
best regards

**Comment by sdimantsd** [comment]
It's look like there is a problem with you're  annotations

**Comment by SylvainArd** [comment]
yes it is, I fixed my annotations and it fixes the bug
Sylvain Ard
0549507724
0778380991
sylvain.ard@gmail.com
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by 007maddycode** [comment]
Hi, 

I came across the same bug. However, I think my annotations are fine. Can you explain where this bug comes from and what you fixed in your annotations to solve the bug? Kind regards

**Comment by SylvainArd** [comment]
add
boxes=boxes.astype("float64")####Ajouté par Sylvain Ard
in the line 168 of utils/augmentation.py
best regards

**Comment by SylvainArd** [comment]
before
boxes[:, [0, 2]] *= (width  / img_w)
boxes[:, [1, 3]] *= (height / img_h)

**Comment by SylvainArd** [comment]
I forgot to precise that I did that to fix the bug

**Comment by 007maddycode** [comment]
The conversion to float64 worked. Thank you very much!

**Comment by sudecki30** [comment]
Hi, i have the same error, but not from box : 

_    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'_

I don't find yet a solution, can you help me?
