### ISSUE TITLE
RuntimeError: strides[cur-1] == sizes[cur]*strides[cur] ASSERT FAILED at /pytorch/torch/csrc/jit/fuser/executor.cpp:149, please report a bug to PyTorch. 

### ISSUE THREAD

**Issue by zhangyueyjy** [dbolya/yolact#611]
Hello,I am getting the error while training the model on custom dataset.

CUDA_VISIBLE_DEVICES=3 python train.py --config=yolact_base_config.

error:
Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 387, in <module>
    train()
  File "train.py", line 310, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 380, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/liangjx/projects/yolact/eval.py", line 875, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/liangjx/projects/yolact/eval.py", line 410, in prep_metrics
    bbox_iou_cache = bbox_iou(boxes.float(), gt_boxes.float())
  File "/home/liangjx/projects/yolact/eval.py", line 363, in bbox_iou
    ret = jaccard(bbox1, bbox2, iscrowd)
  File "/home/liangjx/projects/yolact/layers/box_utils.py", line 73, in jaccard
    inter = intersect(box_a, box_b)
  File "/home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: strides[cur-1] == sizes[cur]*strides[cur] ASSERT FAILED at /pytorch/torch/csrc/jit/fuser/executor.cpp:149, please report a bug to PyTorch. (compressContiguous at /pytorch/torch/csrc/jit/fuser/executor.cpp:149)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f4c2fe7e021 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f4c2fe7d8ea in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x7c691e (0x7f4c2589a91e in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x7c6b59 (0x7f4c2589ab59 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #4: torch::jit::fuser::launchFusion(torch::jit::fuser::FusedKernel const&, c10::Device, c10::ArrayRef<at::Tensor> const&, std::vector<at::Tensor, std::allocator<at::Tensor> >&) + 0xa00 (0x7f4c2589b570 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #5: torch::jit::fuser::runFusion(long, std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0xcf3 (0x7f4c2589caa3 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #6: torch::jit::runFusion(long, std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x11 (0x7f4c257be7d1 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #7: <unknown function> + 0x6f5cf8 (0x7f4c257c9cf8 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #8: <unknown function> + 0x672286 (0x7f4c25746286 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #9: torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x22 (0x7f4c25741842 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #10: <unknown function> + 0x65c6ac (0x7f4c257306ac in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #11: <unknown function> + 0x3c7b94 (0x7f4c2d0fdb94 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x3ac383 (0x7f4c2d0e2383 in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x11642e (0x7f4c2ce4c42e in /home/liangjx/work_env/unmanned_tensorflow/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #43: __libc_start_main + 0xf0 (0x7f4c363fc840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #44: python() [0x4008b9]

Any help will be appreciated!
Thanks~

**Comment by bose1998** [comment]
Im getting the same error.. has anyone solved it?

**Comment by qianxueqing** [comment]
Im getting the same error.. has anyone solved it?
