### ISSUE TITLE
keyerror while computing the validation mAP

### ISSUE THREAD

**Issue by LaPiova** [dbolya/yolact#617]
I was training exactly based on COCO2017 dataset and annotation, and the training process always met error at 43970 iteration when prompting "computing the validation mAP". The error message is below

Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 505, in <module>
    train()
  File "train.py", line 372, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 493, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/yiyi/vsr-api/craft_segmentation/eval.py", line 981, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/yiyi/vsr-api/craft_segmentation/eval.py", line 451, in prep_metrics
    detections.add_bbox(image_id, classes[i], boxes[i,:],   box_scores[i])
  File "/home/yiyi/vsr-api/craft_segmentation/eval.py", line 339, in add_bbox
    'category_id': get_coco_cat(int(category_id)),
  File "/home/yiyi/vsr-api/craft_segmentation/eval.py", line 317, in get_coco_cat
    return coco_cats[transformed_cat_id]
KeyError: 0

**Comment by BaharehGolchin** [comment]
Hi,

I faced the same error. Can you tackle this issue?

Thanks in advance
