### ISSUE TITLE
Can't train on custom dataset: DataLoader worker process 0. AND object of type 'int' has no len()

### ISSUE THREAD

**Issue by Atonbom** [dbolya/yolact#626]
Hi,

I'm trying to get YOLACT(++) to work with a custom dataset using Google Colab because I don't have acces to a powerfull GPU myself.  When I run `train.py` it loads the .json files from the `config.py` and says "Begin training". But then I get the following error and I have no clue where to start looking or what I'm doing wrong. I googled for both errors but I can't find any specific information on how to solve the issue.

`/content/yolact
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train()
  File "train.py", line 270, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/yolact/data/coco.py", line 94, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/content/yolact/data/coco.py", line 148, in pull_item
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "/content/yolact/data/coco.py", line 148, in <listcomp>
    masks = [self.coco.annToMask(obj).reshape(-1) for obj in target]
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 441, in annToMask
    rle = self.annToRLE(ann)
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 426, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
TypeError: object of type 'int' has no len()`

Could someone please help me out here? If not I will go back to Mask-RCNN but I would like to get this working it annoys me

**Comment by kidpaul94** [comment]
I presume that you are trying to do transfer learning with your own config and dataset. Try to search how to do transfer learning for Yolact++. https://github.com/dbolya/yolact/issues/36 will tell you how to do fine tuning. If you want to only modify the last soft-max layer, https://github.com/dbolya/yolact/issues/334 may be helpful.

On top of this, you need to call pretrained weights when doing the transfer learning (e.g., yolact_resnet50_54_800000.pth)
