### ISSUE TITLE
Exception: input type is not supported. 

### ISSUE THREAD

**Issue by Chirag-v09** [dbolya/yolact#628]
Traceback (most recent call last):                                                                                                                                            File "train.py", line 504, in <module>                                                                                                                                        train()                                                                                                                                                                   File "train.py", line 270, in train                                                                                                                                           for datum in data_loader:                                                                                                                                                 File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__                                                      data = self._next_data()                                                                                                                                                  File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data                                                    return self._process_data(data)                                                                                                                                           File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data                                                 data.reraise()                                                                                                                                                            File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\_utils.py", line 394, in reraise                                                                      raise self.exc_type(msg)                                                                                                                                                Exception: Caught Exception in DataLoader worker process 2.                                                                                                                 Original Traceback (most recent call last):                                                                                                                                   File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop                                               data = fetcher.fetch(index)                                                                                                                                               File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch                                                        data = [self.dataset[idx] for idx in possibly_batched_index]                                                                                                              File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>                                                   data = [self.dataset[idx] for idx in possibly_batched_index]                                                                                                              File "D:\segmentation\yolact++\yolact++\data\coco.py", line 94, in __getitem__                                                                                                im, gt, masks, h, w, num_crowds = self.pull_item(index)                                                                                                                   File "D:\segmentation\yolact++\yolact++\data\coco.py", line 160, in pull_item                                                                                                 masks.append(self.coco.annToMask(obj).reshape(-1))                                                                                                                        File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\pycocotools\coco.py", line 441, in annToMask                                                                rle = self.annToRLE(ann)                                                                                                                                                  File "C:\Users\win\anaconda3\envs\yolact-test\lib\site-packages\pycocotools\coco.py", line 426, in annToRLE                                                                 rles = maskUtils.frPyObjects(segm, h, w)                                                                                                                                  File "pycocotools\_mask.pyx", line 307, in pycocotools._mask.frPyObjects                                                                                                  Exception: input type is not supported.

**Comment by Chirag-v09** [comment]
I get this error when I try to do training on yolact.
I also try yolact++ but the error is the same.

Then I try to find out the image where I get this error and put them separately and try to do training on that separate images dataset at that time training is getting done fine but it causing the error when I'm doing a training on the main dataset.

I also compare the segmentation part of the images where the error comes to the images where the error isn't coming and both are in the same format.

Did anyone get this same error or solve this issue?

**Comment by Chirag-v09** [comment]
I figure it out that what the error comes up here.
You have to make sure that there is no empty list in your annotations i.e [ ].
Thanks
