### ISSUE TITLE
Torch.jit.trace Could not export Python function call '_DCNv2'.

### ISSUE THREAD

**Issue by songkq** [dbolya/yolact#647]
I'd like to export the DCNv2-based model for application in Libtorch. 
Could you please give some advice for this issue? Thank you.

```
Env: 
Ubuntu 18.04
Python 3.8
Torch 1.7.1 
```

```
/workspace/DCNv2/dcn_v2.py:23: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  output = _backend.dcn_v2_forward(
Traceback (most recent call last):
  File "/workspace/deploying/convert2script.py", line 28, in <module>
    traced_script_module.save(f"/workspace/libtorch1.7.1.pt")
  File "/root/anaconda3/lib/python3.8/site-packages/torch/jit/_script.py", line 487, in save
    return self._c.save(*args, **kwargs)
RuntimeError: 
Could not export Python function call '_DCNv2'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
/workspace/DCNv2/dcn_v2.py(161): forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
/workspace/lib/model/base/resblock.py(208): forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py(117): forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
/workspace/model_builders/network.py(635): forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py(934): trace_module
/root/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py(733): trace
/workspace/convert2script.py(19): <module>
```

**Comment by kidpaul94** [comment]
I'm not sure what you are exactly trying to do, but the DCNv2 imported here only supports torch 1.4 and torchvision 0.5. If you want to do something with DCNv2 and higher torch version, you probably need to substitute DCNv2 here with https://github.com/jinfagang/DCNv2_latest
