### ISSUE TITLE
Training error on starting multiprocessing

### ISSUE THREAD

**Issue by berkayytu** [dbolya/yolact#651]
I took a error like this. How can I solve this problem.

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_recursive.py:201: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_recursive.py:201: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_recursive.py:201: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
Traceback (most recent call last):
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

**Comment by MiguelAngeloMartinsRibeiro** [comment]
I have the same problem

**Comment by TharHtetSan-cloudsource** [comment]
I have the same problem, can you solve that?
