### ISSUE TITLE
Unknown CUDA arch (8.6) or GPU not supported

### ISSUE THREAD

**Issue by InvincibleKnight** [dbolya/yolact#655]
Hey! So I am working on a remote server which has GPUs 

`$ nvidia-smi` gives the output: 

```
Tue Jun  8 20:36:54 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3080    Off  | 00000000:3D:00.0 Off |                  N/A |
|  0%   37C    P8    15W / 320W |      0MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3080    Off  | 00000000:3F:00.0 Off |                  N/A |
|  0%   40C    P8    19W / 320W |      0MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3080    Off  | 00000000:40:00.0 Off |                  N/A |
|  0%   36C    P8    16W / 320W |      0MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 3080    Off  | 00000000:41:00.0 Off |                  N/A |
|  0%   40C    P8    19W / 320W |      0MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
and  `nvcc --version` gives the output:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

upon running:

```
cd external/DCNv2
python setup.py build develop
```

I get the following error: 

```

running build
running build_ext
building '_ext' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/me/sda3/prooject/yolact/yolact/external/DCNv2/src -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/TH -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/me/.virtualenvs/yoloact/include -I/usr/include/python3.6m -c /home/me/sda3/project/yolact/yolact/external/DCNv2/src/vision.cpp -o build/temp.linux-x86_64-3.6/home/me/sda3/project/yolact/yolact/external/DCNv2/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/me/sda3/project/yolact/yolact/external/DCNv2/src -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/TH -I/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/me/.virtualenvs/yoloact/include -I/usr/include/python3.6m -c /home/me/sda3/project/yolact/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.cpp -o build/temp.linux-x86_64-3.6/home/me/sda3/project/yolact/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 372, in build_extensions
    build_ext.build_extensions(self)
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
 File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 288, in unix_wrap_compile
    "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
  File "/home/me/.virtualenvs/yoloact/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1027, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported
```
What should I do to fix this? 

Thank you!

**Comment by ruanhailiang** [comment]
Hi,Can you share your solution？
