### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by sagarkalburgi** [dbolya/yolact#663]
I'm getting the following error:

```
Traceback (most recent call last):
  File "yolact_app.py", line 441, in run
    train_script.perform()
  File "C:\Users\Ashwini\yolact\train.py", line 631, in perform
    train()
  File "C:\Users\Ashwini\yolact\train.py", line 343, in train
    for datum in data_loader:
  File "D:\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "D:\anaconda3\envs\yolact\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\envs\yolact\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\envs\yolact\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

Could you help me in solving the error?

**Comment by justinkkgoh** [comment]
I am running into the same problem when trying to run train.py on the COCO dataset. Did you manage to resolve this issue?

**Comment by sagarkalburgi** [comment]
@justinkkgoh I have no memory of this. I have switched to yolov8.

**Comment by imKeith** [comment]
I am running into the same problem.Have you solved the problem?
