### ISSUE TITLE
Issue while running eval.py scripts

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#67]
Hi and thx for this project! 
When i execuding the command:
python3 eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=100 --image=data/yolact_example_0.png:output_image.png

I get the following error :-(

Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 795, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 563, in evalimage
    preds = net(batch)
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact/yolact.py", line 530, in forward
    outs = self.backbone(x)
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact/backbone.py", line 115, in forward
    x = self.conv1(x)
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

can you help me plz?

**Comment by dbolya** [comment]
This looks like an issue with pytorch / your installation. What's your
1. Pytorch version
2. Cuda version
3. and GPU

I have a hunch it may be a compatibility issue.

**Comment by sdimantsd** [comment]
Thanks!
my output:
$ conda list pytorch
# packages in environment at /home/ws/anaconda3:
#
# Name                    Version                   Build  Channel
pytorch                   1.0.1           cuda100py36he554f03_0


$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130


My GPU is 2080 ti

**Comment by dbolya** [comment]
According to [this](https://discuss.pytorch.org/t/a-error-when-using-gpu/32761/24), other people are experiencing the same issue with CUDA 10 and a 20 series card. Perhaps you can try disabling CUDNN benchmark mode like in the thread?

On this line, change `True` to `False`:
https://github.com/dbolya/yolact/blob/13b49d749b734b098a292c8c5226017b344ccc67/eval.py#L992

See if that works for you.

**Comment by sdimantsd** [comment]
Result:
$ python eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=100 --image=data/yolact_example_0.png
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

**Comment by dbolya** [comment]
Hmm okay I guess not. How about you install pytorch with pip instead of anaconda? Uninstall pytorch in anaconda and then run:
```
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu100/stable
```
or pip3 if pip doesn't work.

**Comment by sdimantsd** [comment]
Same problem...
$ python3 eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=100 --image=data/yolact_example_0.png
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 797, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 563, in evalimage
    preds = net(batch)
  File "/home/ws/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact/yolact.py", line 530, in forward
    outs = self.backbone(x)
  File "/home/ws/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact/backbone.py", line 115, in forward
    x = self.conv1(x)
  File "/home/ws/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

**Comment by dbolya** [comment]
Okay very weird. Real quick can you run this in a python shell:
```
import torch
print(torch.__version__)
print(torch.version.cuda)
```
Maybe Pytorch isn't using the correct version?

**Comment by sdimantsd** [comment]
>>> import torch
>>> print(torch.__version__)
1.0.0
>>> print(torch.version.cuda)
None
>>>

**Comment by sdimantsd** [comment]
>>> import torch
>>> print(torch.__version__)
1.0.1
>>> print(torch.version.cuda)
9.0.176

Why is the CUDA version is 9?

**Comment by sdimantsd** [comment]
OK, 
I installed torch from here (with CUDA 10.0):
https://pytorch.org/get-started/locally/
and now it's work.

Thanks!!!

**Comment by SnehaTri** [comment]
i am facing following error while inferring dataset of 3700 images and trying to get coco json

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading model... Done.

Traceback (most recent call last):
  File "/content/yolact/eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "/content/yolact/eval.py", line 956, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/content/yolact/eval.py", line 427, in prep_metrics
    detections.add_bbox(image_id, classes[i], boxes[i,:],   box_scores[i])
  File "/content/yolact/eval.py", line 315, in add_bbox
    'category_id': get_coco_cat(int(category_id)),
  File "/content/yolact/eval.py", line 293, in get_coco_cat
    return coco_cats[transformed_cat_id]
KeyError: 2

**Comment by areebsyed** [comment]
@SnehaTri did you find the solution to this
