### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 37.37 GiB (GPU 0; 7.79 GiB total capacity; 1.40 GiB already allocated; 4.21 GiB free; 1.18 GiB cached)

### ISSUE THREAD

**Issue by mortal-Zero** [dbolya/yolact#697]
environment:
  Ubuntu18.04
  GeForce 2080 8G * 2
  python3.7
  torch  1.0.1
  torchvision  0.2.2

When I use my own coco data set for training, the following error will be reported in the second epoch of training every time. During training, I used "nvidia-smi" to check the memory usage and found that it only occupies about 2G of video memory.
Hope you can help me solve this problem.

Traceback (most recent call last):
  File "train.py", line 548, in <module>
    train()
  File "train.py", line 401, in train
    epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 532, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/media/allen/2c10efb5-509a-4697-a3f9-69d83825a4d6/yolact-torch/eval.py", line 995, in evaluate
    w, num_crowd, dataset.ids[image_idx], detections)
  File "/media/allen/2c10efb5-509a-4697-a3f9-69d83825a4d6/yolact-torch/eval.py", line 420, in prep_metrics
    dets, w, h, crop_masks=args.crop, score_threshold=args.score_threshold)
  File "/media/allen/2c10efb5-509a-4697-a3f9-69d83825a4d6/yolact-torch/layers/output_utils.py", line 91, in postprocess
    masks = F.interpolate(masks.unsqueeze(0), (h, w), mode=interpolation_mode, align_corners=False).squeeze(0)
  File "/home/allen/miniconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/functional.py", line 2447, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 37.37 GiB (GPU 0; 7.79 GiB total capacity; 1.40 GiB already allocated; 4.21 GiB free; 1.18 GiB cached)

![image](https://user-images.githubusercontent.com/61569900/138642137-d20f8cc5-b1cf-45f6-a728-5c1f0fcfdfe2.png)

**Comment by vijay180396** [comment]
i have same error

**Comment by Baiyixuan1113** [comment]
> i have same error on second iteration, so how many classes you are using and how many images are you try to train?

I found my problem was that the default 'validation_size' were too large, and the validation_epoch is 2, so at the end of the second epoch of training, it will enter the verification stage, then OOM.
My training config is:
  input_size: 550
  batch_size: 16
  class: 36

 hope that will help you.

**Comment by vijay180396** [comment]
thank for reply

**Comment by vijay180396** [comment]
where can i find validation size in config.py?

**Comment by Baiyixuan1113** [comment]
> where can i find validation size in config.py?

It's in train.py

**Comment by vijay180396** [comment]
many i know how many images you to train images for 36 classes

**Comment by vijay180396** [comment]
i have reduce validation size from default [5000] to 100 but same cuda memory occurred

**Comment by Baiyixuan1113** [comment]
> i have reduce validation size from default [5000] to 100 but same cuda memory occurred

maybe you can try to give it a value same as batch size.

**Comment by vijay180396** [comment]
yes i tried now with validation size to 1 same cuda memory error

**Comment by Baiyixuan1113** [comment]
> yes i tried now with validation size to 1 same cuda memory error

Please display your complete error message. After all, i'm not the author, so I can only help you as much as possible.

**Comment by vijay180396** [comment]
ok i will show you with screenshot and log

**Comment by samwang90** [comment]
issue#158
