### ISSUE TITLE
when i run eval.py ,it return 'use_maskiou' error

### ISSUE THREAD

**Issue by parksangback** [dbolya/yolact#744]
input is under line
`sudo python eval.py --trained_model=weights/yolact_base_54_800000.pth`
output is under line
`Config not specified. Parsed yolact_base_config from the file name.`

`loading annotations into memory...
Done (t=0.30s)
creating index...
index created!
Loading model...Traceback (most recent call last):
  File "eval.py", line 1097, in <module>
    net = Yolact()
  File "/home/cai/capstone/yolact/yolact.py", line 434, in __init__
    if cfg.use_maskiou:
AttributeError: 'Config' object has no attribute 'use_maskiou'`

what should i do? .
i think the error which is a new

**Comment by parksangback** [comment]
Humm.... sorry for that i removed a file....
It's my mistake which was making the error.
SO i re-installed , it was work!!!!!
