### ISSUE TITLE
eval.py showing invalid load key error

### ISSUE THREAD

**Issue by kenil22s** [dbolya/yolact#768]
Loading model...Traceback (most recent call last):
  File "eval.py", line 1098, in <module>
    net.load_weights(args.trained_model)
  File "/content/yolact/yolact.py", line 479, in load_weights
    state_dict = torch.load(path)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by timothyckl** [comment]
i'm facing the same issue. have you resolved this?

**Comment by timothyckl** [comment]
I fixed this issue by re-downloading the model file
