### ISSUE TITLE
Appear during training TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Lalala-ysl** [dbolya/yolact#804]
The following problems occurred when I was training：

[  2]     410 || B: 4.577 | C: 2.328 | M: 7.811 | S: 0.050 | T: 14.766 || ETA: 4 days, 2:55:32 || timer: 0.608
[  2]     420 || B: 4.618 | C: 2.325 | M: 7.860 | S: 0.050 | T: 14.853 || ETA: 4 days, 2:48:44 || timer: 0.657
[  2]     430 || B: 4.612 | C: 2.325 | M: 7.808 | S: 0.051 | T: 14.796 || ETA: 4 days, 2:28:41 || timer: 0.601
[  2]     440 || B: 4.603 | C: 2.325 | M: 7.768 | S: 0.051 | T: 14.747 || ETA: 4 days, 2:46:51 || timer: 1.467
[  2]     450 || B: 4.623 | C: 2.320 | M: 7.814 | S: 0.050 | T: 14.807 || ETA: 4 days, 2:59:56 || timer: 0.611
[  2]     460 || B: 4.672 | C: 2.316 | M: 7.831 | S: 0.049 | T: 14.868 || ETA: 4 days, 3:04:53 || timer: 1.022
[  2]     470 || B: 4.691 | C: 2.315 | M: 7.838 | S: 0.048 | T: 14.892 || ETA: 4 days, 3:13:15 || timer: 1.522
[  2]     480 || B: 4.714 | C: 2.318 | M: 7.837 | S: 0.048 | T: 14.918 || ETA: 4 days, 2:57:20 || timer: 0.598
[  3]     490 || B: 4.693 | C: 2.317 | M: 7.804 | S: 0.049 | T: 14.864 || ETA: 4 days, 3:07:26 || timer: 0.638
Saving state, iter: 500

Computing validation mAP (this may take a while)...
Traceback (most recent call last):
  File "train.py", line 515, in <module>
    train()
  File "train.py", line 379, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 504, in compute_validation_map
    log.log('val', val_info, elapsed=(end - start), epoch=epoch, iter=iteration)
  File "/home/vicky/ysl/yolact/yolact-master/utils/logger.py", line 111, in log
    kwdargs.update(data)
TypeError: 'NoneType' object is not iterable

Thank you for your help.

**Comment by Jie-Huangi** [comment]
I also meet this question. Could you have addressed this.

**Comment by Lalala-ysl** [comment]
> I also meet this question. Could you have addressed this.

it is easily to slove that ,you can check your dataset

**Comment by Jie-Huangi** [comment]
May be I can address this question. 
```py
parser.add_argument('--image', default=None, type=str,
                        help='A path to an image to use for display.')
```
To set like about, may be to work.

**Comment by so-wee** [comment]
> I also meet this question. Could you have addressed this.

请问您解决了吗
