### ISSUE TITLE
IndexError 

### ISSUE THREAD

**Issue by justinkkgoh** [dbolya/yolact#819]
I am trying to run eval.py on my own dataset and initially ran into a size mismatch error as described here #36. However I am now getting this IndexError. Am wondering if anybody else encountered a similar issue? 

`Loading model...Ignoring "Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([33, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([243, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([33]) from checkpoint, the shape in current model is torch.Size([243]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([10, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([80])."
 Done.

Traceback (most recent call last):
  File "/content/yolact/eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "/content/yolact/eval.py", line 956, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/content/yolact/eval.py", line 468, in prep_metrics
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range`

**Comment by KennyChen880127** [comment]
Do your custom config 'dataset''s name == 'num_classes': len('dataset''s name.class_names)+1?
