### ISSUE TITLE
"mtrand.pyx", line 936, in numpy.random.mtrand.RandomState.choice

### ISSUE THREAD

**Issue by sabdha** [dbolya/yolact#843]
I am facing the below error when I start training. There was no issue before.
Begin training!

Traceback (most recent call last):
  File "/content/drive/MyDrive/yolact/./train.py", line 504, in <module>
    train()
  File "/content/drive/MyDrive/yolact/./train.py", line 270, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/yolact/data/coco.py", line 94, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/content/drive/MyDrive/yolact/data/coco.py", line 158, in pull_item
    img, masks, boxes, labels = self.transform(img, masks, target[:, :4],
  File "/content/drive/MyDrive/yolact/utils/augmentations.py", line 688, in __call__
    return self.augment(img, masks, boxes, labels)
  File "/content/drive/MyDrive/yolact/utils/augmentations.py", line 55, in __call__
    img, masks, boxes, labels = t(img, masks, boxes, labels)
  File "/content/drive/MyDrive/yolact/utils/augmentations.py", line 309, in __call__
    mode = random.choice(self.sample_options)
  File "mtrand.pyx", line 936, in numpy.random.mtrand.RandomState.choice
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

**Comment by sabdha** [comment]
This issue got resolved when I downgraged numpy to 1.23.2.

**Comment by pipi0816** [comment]
thanks

**Comment by San-dow** [comment]
问题根源:
np.random.choice(a, p=prob) 要求：
如果 a 是数组，则所有元素必须是 相同形状（不能有些是 [1,2,3]，有些是 [4,5]）。
如果 a 是整数（如 np.random.choice(10, p=prob)），则视为从 np.arange(10) 选择。
但你的 a=self.samplelist 是 变长列表的数组，导致 numpy 无法处理。

 解决方案--改用索引采样（推荐）
既然 self.samplelist 是变长列表，最安全的方法是：
用 np.random.choice 随机选择一个 索引。
通过索引获取对应的列表。
python:
idx = np.random.choice(len(self.samplelist), p=self.sample_p)  # 选择索引
sample = self.samplelist[idx]  # 获取对应的变长列表
优点：
完全规避 np.random.choice 对变长数组的限制。
逻辑清晰，直接按概率分布采样。
