### ISSUE TITLE
python setup.py build develop failed

### ISSUE THREAD

**Issue by Ragnar7982** [dbolya/yolact#849]
Hello, I wanna use yolact++,Here is my PC version, Ubuntu22.04, cuda11.7, torch 1.13.0+cu117, torchvision 0.14.0+cu117, I already follow the steps, when I try python setup.py build develop, it shows:
running build
running build_ext
building '_ext' extension
Emitting ninja build file /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/5] /usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.o 
/usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu:7:10: fatal error: THC/THC.h: No such file or directory
    7 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/5] /usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o 
/usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu:18:10: fatal error: THC/THC.h: No such file or directory
   18 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/5] /usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.o 
/usr/local/cuda-11.7/bin/nvcc  -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/ragnar/yolact/external/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu:9:10: fatal error: THC/THC.h: No such file or directory
    9 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[4/5] c++ -MMD -MF /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.o.d -pthread -B /home/ragnar/anaconda3/envs/yolact/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.cpp -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[5/5] c++ -MMD -MF /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/vision.o.d -pthread -B /home/ragnar/anaconda3/envs/yolact/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ragnar/yolact/external/DCNv2/src -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/TH -I/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/ragnar/anaconda3/envs/yolact/include/python3.7m -c -c /home/ragnar/yolact/external/DCNv2/src/vision.cpp -o /home/ragnar/yolact/external/DCNv2/build/temp.linux-x86_64-cpython-37/home/ragnar/yolact/external/DCNv2/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h: In function ‘at::Tensor dcn_v2_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:25:19: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   25 |     if (input.type().is_cuda())
      |         ~~~~~~~~~~^~
In file included from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ragnar/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:216:30: note: declared here
  216 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::vector<at::Tensor> dcn_v2_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:54:19: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   54 |     if (input.type().is_cuda())
      |         ~~~~~~~~~~^~
In file included from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ragnar/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:216:30: note: declared here
  216 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:88:19: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   88 |     if (input.type().is_cuda())
      |         ~~~~~~~~~~^~
In file included from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ragnar/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:216:30: note: declared here
  216 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:124:19: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  124 |     if (input.type().is_cuda())
      |         ~~~~~~~~~~^~
In file included from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ragnar/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/ragnar/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/ragnar/yolact/external/DCNv2/src/vision.cpp:2:
/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:216:30: note: declared here
  216 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
    depends=ext.depends,
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/ragnar/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Someone please help me!!

**Comment by exorevan** [comment]
Did you find any way to solve this problem except changing versions of the libraries?

**Comment by Ragnar7982** [comment]
Yes, you have to add an argument in setup.py,it's something about GPU sm. I forgot and don't have PC atm.

**Comment by exorevan** [comment]
But external/DCNv2/setup.py doesn't take any arguments

**Comment by Ragnar7982** [comment]
extra_compile_args["nvcc"] = [
            "-DCUDA_HAS_FP16=1",
            "-D__CUDA_NO_HALF_OPERATORS__",
            "-D__CUDA_NO_HALF_CONVERSIONS__",
            "-D__CUDA_NO_HALF2_OPERATORS__",
        ]
Something have to add here, but I don't have PC atm, what's your GPU?

**Comment by Ragnar7982** [comment]
https://github.com/CharlesShang/DCNv2/issues/88#issuecomment-1005358220
Maybe you can try this.
